[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  "pip install --no-cache-dir \"google-cloud-aiplatform>=1.71.1\""
]

[start]
cmd = "python bot.py"